# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:11.3-alpine
    environment:
      POSTGRES_DB: coffee_dev
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      
volumes:
  postgresql:
  postgresql_data: